---
title: "Wildland Fire Population Density"
author: "Matthew Wallace"
date: "2024-11-29"
output: pdf_document
---

### Libraries

```{r}
library(dplyr)
library(tigris)
library(sf)
library(ggplot2)
library(tidycensus)
library(spatstat)
library(spmodel)
library(cowplot)

library(patchwork)
library(imager)
library(terra)
library(scales)
library(readr)
library(tidyverse)
```

### Data Loading

```{r}
# Arizona
load("wfigs_az_sf_EPSG32612.RData")
st_crs(wfigs_az_sf) <- 32612
az_fires_rx <- wfigs_az_sf %>% filter(IncidentTypeCategory=="RX")
az_fires_wf <- wfigs_az_sf %>% filter(IncidentTypeCategory=="WF")

az_fires_wf_hum <- az_fires_wf %>% filter(FireCause=="Human")
az_fires_wf_nat <- az_fires_wf %>% filter(FireCause=="Natural")
az_fires_wf_un <- az_fires_wf %>% filter(FireCause=="Undetermined" | FireCause=="Unknown")

# Coconino
coconino_sf <- counties(state = "AZ") %>%
  filter(NAME == "Coconino")
coconino_sf <- st_transform(coconino_sf, 32612)
wfigs_coco_sf <- wfigs_az_sf %>%
  st_filter(coconino_sf, .predicate = st_within)

coco_fires_rx <- wfigs_coco_sf %>% filter(IncidentTypeCategory=="RX")
coco_fires_wf <- wfigs_coco_sf %>% filter(IncidentTypeCategory=="WF")

coco_fires_wf_hum <- coco_fires_wf %>% filter(FireCause=="Human")
coco_fires_wf_nat <- coco_fires_wf %>% filter(FireCause=="Natural")
coco_fires_wf_un <- coco_fires_wf %>% filter(FireCause=="Undetermined" | FireCause=="Unknown")

coco_fires_wf_hum_lg <- coco_fires_wf_hum %>% filter(IncidentSize >= 1000)
coco_fires_wf_hum_sm <- coco_fires_wf_hum %>% filter(IncidentSize < 1000)
coco_fires_wf_nat_lg <- coco_fires_wf_nat %>% filter(IncidentSize >= 1000)
coco_fires_wf_nat_sm <- coco_fires_wf_nat %>% filter(IncidentSize < 1000)

coconino.bbox <- st_bbox(coconino_sf)
coco_pred.owin <- as.owin(coconino_sf)
```

### Population Density Exploration

```{r}
population_data <- get_decennial(
  geography = "tract",
  variables = c(population="P001001"),
  state = "AZ",
  year = 2010,
  geometry = TRUE
)
population_data$value[population_data$value==0] <- 1
population_data$variable <-  population_data$value/st_area(population_data$geometry)
names(population_data) <- c("GEOID","NAME","pop.density","pop.","geometry")

ggplot() +
  geom_sf(aes(fill=as.numeric(log(pop.density))), data=population_data) +
  geom_sf(data=az_fires_wf_hum, alpha=0.1, col="indianred") +
  scale_fill_viridis_c() +
  labs(fill = "Log\nPopulation\nDensity", title="Human Caused Wildfires") +
  theme_minimal()

ggplot() +
  geom_sf(aes(fill=as.numeric(log(pop.density))), data=population_data) +
  geom_sf(data=az_fires_wf_nat, alpha=0.1, col="indianred") +
  scale_fill_viridis_c() +
  labs(fill = "Log\nPopulation\nDensity", title="Natural Wildfires") +
  theme_minimal()

hist(population_data$pop.density)
hist(log(population_data$pop.density))
```

### Prediction Grid Data

# Response

```{r}
# Human Caused PPP
coco_wf.ppp <- as.ppp(coco_fires_wf, W=coco_pred.owin)
coco_wf_hum.ppp <- as.ppp(coco_fires_wf_hum, W=coco_pred.owin)
coco_wf_hum_lg.ppp <- as.ppp(coco_fires_wf_hum_lg, W=coco_pred.owin)
coco_wf_hum_sm.ppp <- as.ppp(coco_fires_wf_hum_sm, W=coco_pred.owin)

# Natural PPP
coco_wf_nat.ppp <- as.ppp(coco_fires_wf_nat, W=coco_pred.owin)
coco_wf_nat_lg.ppp <- as.ppp(coco_fires_wf_nat_lg, W=coco_pred.owin)
coco_wf_nat_sm.ppp <- as.ppp(coco_fires_wf_nat_sm, W=coco_pred.owin)

# Human Caused Data Frames
coco_wf_hum.df <- data.frame(x = coco_wf_hum.ppp$x, y = coco_wf_hum.ppp$y)
coco_wf_hum_lg.df <- data.frame(x = coco_wf_hum_lg.ppp$x, y = coco_wf_hum_lg.ppp$y)
coco_wf_hum_sm.df <- data.frame(x = coco_wf_hum_sm.ppp$x, y = coco_wf_hum_sm.ppp$y)

# Natural Data Frames
coco_wf_nat.df <- data.frame(x = coco_wf_nat.ppp$x, y = coco_wf_nat.ppp$y)
coco_wf_nat_lg.df <- data.frame(x = coco_wf_nat_lg.ppp$x, y = coco_wf_nat_lg.ppp$y)
coco_wf_nat_sm.df <- data.frame(x = coco_wf_nat_sm.ppp$x, y = coco_wf_nat_sm.ppp$y)

# Create individual plots
hum_plot <- ggplot() +
  geom_sf(data = coconino_sf, fill = "white", color = "black", alpha = 0.5) +
  geom_point(data = coco_wf_hum.df, aes(x = x, y = y), color = "indianred", size = 1) +
  theme_minimal() +
  labs(title = "Coconino All Human Caused Wildfires", x = "Longitude", y = "Latitude")

hum_lg_plot <- ggplot() +
  geom_sf(data = coconino_sf, fill = "white", color = "black", alpha = 0.5) +
  geom_point(data = coco_wf_hum_lg.df, aes(x = x, y = y), color = "indianred", size = 1) +
  theme_minimal() +
  labs(title = "Coconino Large Human Caused Wildfires", x = "Longitude", y = "Latitude")

hum_sm_plot <- ggplot() +
  geom_sf(data = coconino_sf, fill = "white", color = "black", alpha = 0.5) +
  geom_point(data = coco_wf_hum_sm.df, aes(x = x, y = y), color = "indianred", size = 1) +
  theme_minimal() +
  labs(title = "Coconino Small Human Caused Wildfires", x = "Longitude", y = "Latitude")

nat_plot <- ggplot() +
  geom_sf(data = coconino_sf, fill = "white", color = "black", alpha = 0.5) +
  geom_point(data = coco_wf_nat.df, aes(x = x, y = y), color = "indianred", size = 1) +
  theme_minimal() +
  labs(title = "Coconino All Natural Wildfires", x = "Longitude", y = "Latitude")

nat_lg_plot <- ggplot() +
  geom_sf(data = coconino_sf, fill = "white", color = "black", alpha = 0.5) +
  geom_point(data = coco_wf_nat_lg.df, aes(x = x, y = y), color = "indianred", size = 1) +
  theme_minimal() +
  labs(title = "Coconino Large Natural Wildfires", x = "Longitude", y = "Latitude")

nat_sm_plot <- ggplot() +
  geom_sf(data = coconino_sf, fill = "white", color = "black", alpha = 0.5) +
  geom_point(data = coco_wf_nat_sm.df, aes(x = x, y = y), color = "indianred", size = 1) +
  theme_minimal() +
  labs(title = "Coconino Small Natural Wildfires", x = "Longitude", y = "Latitude")

# Arrange in a 2x3 grid
(hum_plot | hum_lg_plot | hum_sm_plot | nat_plot | nat_lg_plot | nat_sm_plot)
```

# Predictors

```{r}
load("az_prediction_grid_sf.RData")
get_im <- function(x){
  coconino.owin <- owin(yrange = c(coconino.bbox["xmin"], coconino.bbox["xmax"]),
                        xrange = c(-coconino.bbox["ymax"], -coconino.bbox["ymin"]))
  rast <- rast(extent = coconino.bbox, res = 15000)
  rasterized <- rasterize(az_prediction_grid_sf, rast, field=x)
  matrix <- t(as.matrix(rasterized, wide=TRUE))
  im <- rotate.im(as.im(matrix, W=coconino.owin), angle = -pi/2)
  return(im)
}
predictors <- c("mean_slope",
                "Elevation",
                "mean_forest",
                "mean_grass",
                "Temp_Max_Buffered",
                "Temp_Min_Buffered",
                "Precipitation_Buffered",
                "pop.density",
                "distance_rd_primary",
                "distance_rd_secondary",
                "distance_rd_4wd",
                "distance_rd_min_prisec",
                "distance_rd_min_all",
                "distance_rd_min_isprisec")

pred_titles <- c("Slope",
                 "Elevation",
                 "Forest",
                 "Grass",
                 "Maximum Temperature",
                 "Minimum Temperature",
                 "Precipitation",
                 "Population Density",
                 "Distance to Primary Road",
                 "Distance to Secondary Road",
                 "Distance to Remote Road",
                 "Minimum Distance to\nPrimary or Secondary Road",
                 "Minimum Distance to any Road",
                 "The Closest Road is\nPrimary or Secondary Road")
par(mfrow=c(4,4),
    mar = c(1, 1, 1, 1),
    oma = c(1, 1, 1, 1))
for (i in 1:length(predictors)){
  plot(get_im(predictors[i]), main=pred_titles[i])
}

predictors.im <- lapply(predictors, get_im)
names(predictors.im) <- predictors
```

### Models

## Human Caused

# All Wildfires

```{r}
# Fitting
coco_wf_hum.kppm <- kppm(unmark(coco_wf_hum.ppp)~., data=predictors.im, clusters = "LGCP", model = "exponential")
#step(coco_wf_hum.kppm)

plot(predict(coco_wf_hum.kppm, eps = 15000))
points(st_coordinates(coco_fires_wf_hum), col="white")
```

# Thresholded Wildfires

```{r}
# Fitting
coco_wf_hum_lg.kppm <- kppm(unmark(coco_wf_hum_lg.ppp)~., data=predictors.im, clusters = "LGCP", model = "exponential")
plot(predict(coco_wf_hum_lg.kppm, eps = 15000))
points(st_coordinates(coco_fires_wf_hum_lg), col="white")

coco_wf_hum_sm.kppm <- kppm(unmark(coco_wf_hum_sm.ppp)~., data=predictors.im, clusters = "LGCP", model = "exponential")
plot(predict(coco_wf_hum_sm.kppm, eps = 15000))
points(st_coordinates(coco_fires_wf_hum_sm), col="white")
```


## Natural

# All Wildfires

```{r}
# Fitting
coco_wf_nat.kppm <- kppm(unmark(coco_wf_nat.ppp)~., data=predictors.im, clusters = "LGCP", model = "exponential")
#step(coco_wf_nat.kppm)

plot(predict(coco_wf_nat.kppm, eps = 15000))
points(st_coordinates(coco_fires_wf_nat), col="white")
```

# Threshold Wilfires

```{r}
coco_wf_nat_lg.kppm <- kppm(unmark(coco_wf_nat_lg.ppp)~., data=predictors.im, clusters = "LGCP", model = "exponential")
plot(predict(coco_wf_nat_lg.kppm, eps = 15000))
points(st_coordinates(coco_fires_wf_nat_lg), col="white")

coco_wf_nat_sm.kppm <- kppm(unmark(coco_wf_nat_sm.ppp)~., data=predictors.im, clusters = "LGCP", model = "exponential")
plot(predict(coco_wf_nat_sm.kppm, eps = 15000))
points(st_coordinates(coco_fires_wf_nat_sm), col="white")
```

### CSR Analysis

## Setup

```{r}
coco_wf_hum_naive.kppm <- kppm(unmark(coco_wf_hum.ppp)~1, clusters = "LGCP", model = "exponential")
coco_wf_hum_lg_naive.kppm <- kppm(unmark(coco_wf_hum_lg.ppp)~1, clusters = "LGCP", model = "exponential")
coco_wf_hum_sm_naive.kppm <- kppm(unmark(coco_wf_hum_sm.ppp)~1, clusters = "LGCP", model = "exponential")
coco_wf_nat_naive.kppm <- kppm(unmark(coco_wf_nat.ppp)~1, clusters = "LGCP", model = "exponential")
coco_wf_nat_lg_naive.kppm <- kppm(unmark(coco_wf_nat_lg.ppp)~1, clusters = "LGCP", model = "exponential")
coco_wf_nat_sm_naive.kppm <- kppm(unmark(coco_wf_nat_sm.ppp)~1, clusters = "LGCP", model = "exponential")

plot_envelopes <- function(naive.kppm, model.kppm, title){
  plot(envelope(naive.kppm, fun = Fest),
     col = c("black","darkgreen", NA, NA),
     shadecol = adjustcolor("gray", 0.5),
     lwd = 2, legend = F, main = title)
  plot(envelope(model.kppm, fun = Fest),
     col = c(NA, "darkred", NA, NA),
     shadecol = adjustcolor("gray", 0.5),
     lwd = 2, add = T)
  legend("topleft", legend=c("Intercept", "KPPM"),
       col=c("darkgreen", "darkred"), lty=2)
  
  plot(envelope(naive.kppm, fun = Gest),
     col = c("black","darkgreen", NA, NA),
     shadecol = adjustcolor("gray", 0.5),
     lwd = 2, legend = F, main = title)
  plot(envelope(model.kppm, fun = Fest),
     col = c(NA, "darkred", NA, NA),
     shadecol = adjustcolor("gray", 0.5),
     lwd = 2, add = T)
  legend("topleft", legend=c("Intercept", "KPPM"),
       col=c("darkgreen", "darkred"), lty=2)
}
```

## Human Caused

# All

```{r}
plot_envelopes(coco_wf_hum_naive.kppm, coco_wf_hum.kppm, "All Human Caused")
```

# Threshold

```{r}
plot_envelopes(coco_wf_hum_lg_naive.kppm, coco_wf_hum_lg.kppm, "Large Human Caused")
plot_envelopes(coco_wf_hum_sm_naive.kppm, coco_wf_hum_sm.kppm, "Small Human Caused")
```

## Natural

# All

```{r}
plot_envelopes(coco_wf_nat_naive.kppm, coco_wf_nat.kppm, "All Natural")
```

# Threshold

```{r}
plot_envelopes(coco_wf_nat_lg_naive.kppm, coco_wf_nat_lg.kppm, "Large Natural")
plot_envelopes(coco_wf_nat_sm_naive.kppm, coco_wf_nat_sm.kppm, "Small Natural")
```

## All Parameters

```{r}
rbind("All Human Caused" = coco_wf_hum.kppm$par,
       "Large Human Caused" = coco_wf_hum_lg.kppm$par,
       "Small Human Caused" = coco_wf_hum_sm.kppm$par,
       "All Natural" = coco_wf_nat.kppm$par,
       "Large Natural" = coco_wf_nat_lg.kppm$par,
       "Small Natural" = coco_wf_nat_sm.kppm$par)
```


## All Plots

```{r}
par(mfcol = c(2, 6), mar = c(1, 1, 1, 1))
plot_envelopes(coco_wf_hum_naive.kppm, coco_wf_hum.kppm, "All Human Caused")
plot_envelopes(coco_wf_hum_lg_naive.kppm, coco_wf_hum_lg.kppm, "Large Human Caused")
plot_envelopes(coco_wf_hum_sm_naive.kppm, coco_wf_hum_sm.kppm, "Small Human Caused")
plot_envelopes(coco_wf_nat_naive.kppm, coco_wf_nat.kppm, "All Natural")
plot_envelopes(coco_wf_nat_lg_naive.kppm, coco_wf_nat_lg.kppm, "Large Natural")
plot_envelopes(coco_wf_nat_sm_naive.kppm, coco_wf_nat_sm.kppm, "Small Natural")
```

## All of Arizona CSR

```{r}
az_wf_hum.ppp <- as.ppp(az_fires_wf_hum)
az_wf_nat.ppp <- as.ppp(az_fires_wf_nat)

az_wf_hum_naive.kppm <- kppm(unmark(az_wf_hum.ppp)~1, clusters = "LGCP", model = "exponential")
az_wf_nat_naive.kppm <- kppm(unmark(az_wf_nat.ppp)~1, clusters = "LGCP", model = "exponential")

par(mfcol=c(2,2))
plot(envelope(az_wf_hum_naive.kppm, fun = Fest),
   col = c("black","darkgreen", NA, NA),
   shadecol = adjustcolor("gray", 0.5),
   lwd = 2, legend = F, main = "All AZ Human Caused")
plot(envelope(az_wf_hum_naive.kppm, fun = Gest),
   col = c("black","darkgreen", NA, NA),
   shadecol = adjustcolor("gray", 0.5),
   lwd = 2, legend = F, main = "All AZ Human Caused")
plot(envelope(az_wf_nat_naive.kppm, fun = Fest),
   col = c("black","darkgreen", NA, NA),
   shadecol = adjustcolor("gray", 0.5),
   lwd = 2, legend = F, main = "All AZ Natural")
plot(envelope(az_wf_nat_naive.kppm, fun = Gest),
   col = c("black","darkgreen", NA, NA),
   shadecol = adjustcolor("gray", 0.5),
   lwd = 2, legend = F, main = "All AZ Natural")
```

