---
title: "Wildland Fire Incident Locations"
author: "Alex Salce"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    df_print: paged
    theme: cosmo
header-includes:
- \renewcommand*\familydefault{\sfdefault} %% this picks a sans serif font
- \usepackage[T1]{fontenc}
---


## Wildland Fire Incident 

In this section, I put together some visualizations that were interesting to me and to serve as proof-of-concept for combining some data.

```{r warning=FALSE, message=FALSE}

library(dplyr)
library(tigris)
library(sf)
library(ggplot2)
library(mapview)
library(tidyverse)
library(scales)
library(readr)

# load datasets
library(here)
set_here(path='../../')


load(here('data/wfigs_az_sf_EPSG32612.RData'))
load(here('data/az_rd_4WD_EPSG32612.RData'))
load(here('data/az_rd_primary_EPSG32612.RData'))
load(here('data/az_rd_secondary_EPSG32612.RData'))
# wfigs_az_all_cov <- read_csv(here('data/wfigs_az_all_cov.csv'), show_col_types = FALSE)

# wfigs_az_sf <- st_transform(wfigs_az_sf, crs = "EPSG:32612")
# az_rd_primary <- st_transform(az_rd_primary, crs = "EPSG:32612")
# az_rd_secondary <- st_transform(az_rd_secondary, crs = "EPSG:32612")
# az_rd_4wd <- st_transform(az_rd_4wd, crs = "EPSG:32612")

```


```{r wfigs_az_sfCleanup, eval=FALSE, echo=FALSE}

# reference for vars
# https://data-nifc.opendata.arcgis.com/datasets/nifc::wildland-fire-incident-locations/about

# Low hanging fruit (mostly if not all NA)
wfigs_az_sf <- wfigs_az_sf %>% select(-c(ABCDMisc, 
                                         FinalAcres, 
                                         FinalFireReportApprovedByTitle,
                                         FinalFireReportApprovedByUnit,
                                         FinalFireReportApprovedDate, 
                                         FireDepartmentID, 
                                         POOLegalDescQtr, 
                                         POOLegalDescQtrQtr, 
                                         POOLegalDescPrincipalMeridian, 
                                         POOLegalDescRange, 
                                         POOLegalDescSection, 
                                         POOLegalDescTownship, 
                                         CpxName, 
                                         CpxID, 
                                         IncidentComplexityLevel))


# data for this project only
wfigsaz_sf <- wfigs_az_sf %>% select(c(OBJECTID,
                                        IncidentSize,
                                        FireCause,
                                        FireCauseGeneral,
                                        FireCauseSpecific,
                                        FireDiscoveryDateTime,
                                        IncidentName,
                                        IncidentShortDescription,
                                        IncidentTypeCategory,
                                        IncidentTypeKind,
                                        InitialResponseAcres,
                                        InitialResponseDateTime,
                                        IrwinID,
                                        IsFireCauseInvestigated,
                                        POOCity,
                                        POOCounty,
                                        POOFips,
                                        POODispatchCenterID,
                                        PredominantFuelGroup,
                                        PredominantFuelModel,
                                        UniqueFireIdentifier,
                                        EstimatedFinalCost,
                                        79:98
                                        ))

```


```{r finaldataframes}

az_fires_rx <- wfigs_az_sf %>% filter(IncidentTypeCategory=="RX")
az_fires_wf <- wfigs_az_sf %>% filter(IncidentTypeCategory=="WF")


#human caused wildfires

table(wfigs_az_sf$FireCause)

az_fires_wf_hum <- az_fires_wf %>% filter(FireCause=="Human")
az_fires_wf_nat <- az_fires_wf %>% filter(FireCause=="Natural")
az_fires_wf_un <- az_fires_wf %>% filter(FireCause=="Undetermined" | FireCause=="Unknown")


```


```{r thresholding}

####################################
# RUN BELOW FOR FIRE SIZE THRESHOLD#
####################################


# fire size threshold
# FIRE_SIZE_CLASS = Code for fire size based on the number of acres within the 
# final fire perimeter (A=greater than 0 but less than or equal to 0.25 acres, 
# B=0.26-9.9 acres, C=10.0-99.9 acres, D=100-299 acres, E=300 to 999 acres, 
# F=1000 to 4999 acres, and G=5000+ acres).

# class F and G fires
wf_size_threshold <- 1000

# max prescribed burn size
# wf_size_threshold <- max(az_fires_rx$IncidentSize)

wfigs_az_sf_thresh <- wfigs_az_sf %>% filter(IncidentSize >= wf_size_threshold)


az_fires_rx <- wfigs_az_sf_thresh %>% filter(IncidentTypeCategory=="RX")
az_fires_wf <- wfigs_az_sf_thresh %>% filter(IncidentTypeCategory=="WF")


#human caused wildfires

table(wfigs_az_sf_thresh$FireCause)

az_fires_wf_hum <- az_fires_wf %>% filter(FireCause=="Human")
az_fires_wf_nat <- az_fires_wf %>% filter(FireCause=="Natural")
az_fires_wf_un <- az_fires_wf %>% filter(FireCause=="Undetermined" | FireCause=="Unknown")

```

```{r azdata, message=FALSE, warning=FALSE, results='hide', cache=TRUE}

arizona_sf <- states() %>% filter_state("arizona")

az_counties_sf <- counties(state = "AZ", cb = TRUE)

#UTM Zone 12 https://epsg.io/2223

# arizona_sf <- st_transform(arizona_sf, crs = "EPSG:2223")

st_crs(wfigs_az_sf) <- st_crs(arizona_sf)
st_crs(az_counties_sf) <- st_crs(arizona_sf)
st_crs(az_rd_primary) <- st_crs(arizona_sf)
st_crs(az_rd_secondary) <- st_crs(arizona_sf)
st_crs(az_rd_4wd) <- st_crs(arizona_sf)


```



```{r azwildfireplot, fig.align='center', out.width="95%", tidy=TRUE, echo=FALSE, warning=FALSE, message=FALSE, results='hide', cache=TRUE, tidy.opts=list(width.cutoff=70)}

plot(arizona_sf$geometry, main = "Wildfires in Arizona 2014-2024")
plot(az_counties_sf, add=T)
plot(wfigs_az_sf$geometry, pch = 16, cex = 0.4, col = scales::alpha("darkred", 0.1), add = T)

```


```{r roadsfilter, eval=FALSE, echo=FALSE}

az_rd_primary <- az_roads_sf %>% 
  filter(MTFCC %in% c("S1100"))  # Primary  roads

az_rd_secondary <- az_roads_sf %>% 
  filter(MTFCC %in% c("S1200"))  # Secondary roads

az_rd_4wd <- az_roads_sf %>% 
  filter(MTFCC %in% c("S1500"))  # 4WD roads

rm(az_roads_sf)

```

```{r rdanalysismapview, eval=FALSE, echo=FALSE}

# fun interactive version of the map:

mapview(arizona_sf, col.regions = "snow") +
  mapview(az_rd_primary$geometry, color = "green", alpha = 0.8) +
  mapview(az_rd_secondary$geometry, color = "blueviolet", alpha = 0.8) +
  mapview(az_rd_4wd$geometry, col. = "gray", alpha.regions = 0.3)

```

```{r rdanalysisplot, cache=TRUE, echo=FALSE}

#roads used for analysis

plot(arizona_sf$geometry, main = "Primary, Secondary, 4WD roads")
plot(az_rd_primary$geometry, col = "green", add = T, lwd = 0.2)
plot(az_rd_secondary$geometry, col = "blueviolet", add = T, lwd = 0.2)
plot(az_rd_4wd$geometry, col = "gray", add = T, lwd = 0.05)

```

```{r minsaddl, echo=FALSE, eval=FALSE}

wfigs_az_sf <- wfigs_az_sf %>%
  mutate(distance_rd_min_all = pmin(distance_rd_primary, 
                                    distance_rd_secondary, 
                                    distance_rd_4wd))

wfigs_az_sf <- wfigs_az_sf %>%
  mutate(distance_rd_min_prisec = pmin(distance_rd_primary, 
                                    distance_rd_secondary))

wfigs_az_sf$distance_rd_min_isprisec <- as.integer(wfigs_az_sf$distance_rd_min_all ==
                                                     wfigs_az_sf$distance_rd_min_prisec) 

#if want to convert 0s and 1s to string info

wfigs_az_sf <- wfigs_az_sf %>%
  mutate(distance_rd_min_isprisec = case_when(
    distance_rd_min_isprisec == 0 ~ "4wd",
    distance_rd_min_isprisec == 1 ~ "Primary or Secondary",
    TRUE ~ as.character(distance_rd_min_isprisec)
  ))

```


```{r whichrdhist}

table(wfigs_az_sf$distance_rd_min_isprisec)

```

```{r disthists}

histdf <- az_fires_wf_nat

x_rng <- range(c(histdf$distance_rd_primary, 
                 histdf$distance_rd_secondary, 
                 histdf$distance_rd_4wd))
y_max <- max(hist(histdf$distance_rd_primary, plot = FALSE)$counts, 
             hist(histdf$distance_rd_secondary, plot = FALSE)$counts,
             hist(histdf$distance_rd_4wd, plot = FALSE)$counts)


#overlay hist of dist from roads

hist(histdf$distance_rd_primary, col = rgb(1, 0, 0, 0.5), xlim = x_rng, ylim = c(0, y_max),
     main = "Min distance to fires", xlab = "Value")
hist(histdf$distance_rd_secondary, col = rgb(0, 1, 0, 0.5), add = TRUE)
hist(histdf$distance_rd_4wd, col = rgb(0, 0, 1, 0.5), add = TRUE)

# Add a legend
legend("topright", c("Primary Roads", "Secondary Roads", "4WD Roads"),
       fill = c(rgb(1, 0, 0, 0.5), rgb(0, 1, 0, 0.5), rgb(0, 0, 1, 0.5)))

```

```{r disthistsmindistprimsec4wd}

histdf <- az_fires_wf_nat

x_rng <- range(c(histdf$distance_rd_min_all[histdf$distance_rd_min_isprisec==1], 
                 histdf$distance_rd_min_all[histdf$distance_rd_min_isprisec==0]))
y_max <- max(hist(histdf$distance_rd_min_all, plot = FALSE)$counts)


#overlay hist of dist from roads

hist(histdf$distance_rd_min_all[histdf$distance_rd_min_isprisec==1], col = rgb(1, 0, 0, 0.5), xlim = x_rng, ylim = c(0, y_max),
     main = "Min distance to fires", xlab = "Value")
hist(histdf$distance_rd_min_all[histdf$distance_rd_min_isprisec==0], col = rgb(0, 1, 0, 0.5), add = TRUE)

# Add a legend
legend("topright", c("MinDistIsPrimSec", "MinDistIs4WD"),
       fill = c(rgb(1, 0, 0, 0.5), rgb(0, 1, 0, 0.5)))

```






# Counties

```{r cococounty}

# Extract Coconino County
coconino_sf <- az_counties_sf %>% 
  filter(NAME == "Coconino")

# Crop Arizona and counties to the buffered area
arizona_coconino <- st_intersection(arizona_sf, coconino_sf)
counties_coconino <- st_intersection(az_counties_sf, coconino_sf)
wfigs_az_sf_coconino <- st_intersection(wfigs_az_sf, coconino_sf)

```



```{r eval=FALSE, include=FALSE}

# fun interactive version of the map:

mapview(arizona_coconino, col.regions = "snow") +
  mapview(counties_coconino, col.regions = "gray")+
  mapview(az_cc_rd_primary, color = "black", alpha = 0.8) +
  mapview(wfigs_az_sf_coconino, col. = "darkred", alpha.regions = 0.3)

```


```{r eval=FALSE, include=FALSE, fig.align='center', out.width="95%", tidy=TRUE, warning=FALSE, message=FALSE, results='hide', cache=TRUE, tidy.opts=list(width.cutoff=70)}

wfigs_az_lg_sf_coconino <- wfigs_az_sf_coconino %>% filter(IncidentSize >= 1000)

plot(arizona_sf$geometry, main = "Large Wildfires (>1000 acres) in Arizona 2014-2024")
plot(az_counties_sf, add=T)
plot(wfigs_az_lg_sf_coconino$geometry, pch = 16, cex = 0.5, col = scales::alpha("darkred", 0.3), add = T)


# fun interactive version of the map:

mapview(arizona_coconino, col.regions = "snow") +
  mapview(counties_coconino, col.regions = "gray")+
  mapview(az_cc_rd_primary, color = "black", alpha = 0.8) +
  mapview(wfigs_az_lg_sf_coconino, col. = "darkorange", alpha.regions = 0.3)


```


```{r fig.align='center', out.width="95%", tidy=TRUE, warning=FALSE, message=FALSE, results='hide', cache=TRUE, tidy.opts=list(width.cutoff=70)}

wfigs_az_lg_sf <- wfigs_az_sf %>% filter(IncidentSize >= 1000)

plot(arizona_sf$geometry, main = "Large Wildfires (>1000 acres) in Arizona 2014-2024")
plot(az_counties_sf, add=T)
plot(wfigs_az_lg_sf$geometry, pch = 16, cex = 0.5, col = scales::alpha("darkred", 0.3), add = T)


wfigs_az_lg_sf_coconino <- st_intersection(wfigs_az_lg_sf, coconino)

# fun interactive version of the map:

# mapview(arizona_coconino, col.regions = "snow") +
#   mapview(counties_coconino, col.regions = "gray")+
#   mapview(az_cc_major_roads, color = "black", alpha = 0.8) +
#   mapview(az_cc_minor_roads, color = "black", alpha = 0.15) +
#   mapview(wfigs_az_lg_sf_coconino, col. = "darkorange", alpha.regions = 0.3)


```

```{r}

ggplot() +
  geom_sf(data = arizona_sf) +
  geom_sf(data = az_counties_sf, fill = "gray85") +
  # geom_sf(data = az_rd_primary, color="black", linewidth=0.4) +
  # geom_sf(data = az_rd_secondary, color="gray15", linewidth=0.3) +
  geom_sf(data = az_fires_wf, color="orangered", size=0.1, alpha=0.25) +
  # geom_sf(data = az_rd_4wd, color="gray50", linewidth=0.1) +
  # geom_sf(data = wfigs_az_sf[wfigs_az_sf$IncidentSize >= 1000,], size = 0.85, alpha = 0.75, color="orangered") +
  # geom_sf(aes(col=log(IncidentSize)),data = wfigs_az_sf[wfigs_az_sf$IncidentSize >= 1000,], size = 0.8, alpha = 0.75) +
  # scale_color_gradientn(colors = brewer.pal(9, "YlOrRd")) +
  # scale_color_viridis_c(option = "D") +
  # ggtitle("Large Wildfires in Arizona 2014-2024") +
  theme_minimal()


```

```{r}


# Create the base plot
ggplot() +
  geom_sf(data = arizona_sf) +
  geom_sf(data = az_counties_sf, fill = "gray85") +
  geom_sf(data = coconino_sf, fill = "aquamarine3") +
  geom_sf(data = wfigs_az_sf_thresh, color="orangered", size=0.6, alpha=0.75) +
  # geom_sf(data = az_rd_primary, color="black", linewidth=0.2) +
  # geom_sf(data = az_rd_secondary, color="gray15", linewidth=0.1) +
  ggtitle("Wildfires in Arizona 2014-2024") +
  theme_minimal()

wfigs_cc_sf <- st_intersection(wfigs_az_sf, coconino_sf)

ggplot() +
  geom_sf(data = coconino_sf) +
  # geom_sf(data = az_counties_sf, fill = "gray85") +
  geom_sf(data = wfigs_cc_sf, color="orangered", size=0.25, alpha=0.25) +
  # geom_sf(data = az_rd_primary, color="black", linewidth=0.2) +
  # geom_sf(data = az_rd_secondary, color="gray15", linewidth=0.1) +
  theme_minimal()
  



```


```{r builddataspglmppp, cache=TRUE, warning=FALSE, message=FALSE}

# set seed to 219 for report!
set.seed(219)

# set seed to 20 for predictions!
# set.seed(20)

# pick df of interest

az_fires_wf_spglm <- az_fires_wf_nat


az_fires_wf_spglm_ppp <- as.ppp(az_fires_wf_spglm)

background <- rpoispp((az_fires_wf_spglm_ppp$n) / area(as.owin(az_fires_wf_spglm_ppp)),
                      win = as.owin(coconino_sf))

df <- data.frame(x = background$x, y = background$y)

background_sf <- st_as_sf(df, coords = c("x", "y"), crs = "EPSG:32612")

```

```{r azccplotppp}

wf_sf_cc_plot <- st_as_sf(as.data.frame(az_fires_wf_spglm_ppp), coords = c("x", "y"), crs="EPSG:32612")

wf_sf_cc_plot <- st_transform(wf_sf_cc_plot, crs = 4326)

bkg_sf_cc_plot <- st_as_sf(as.data.frame(background), coords = c("x", "y"), crs="EPSG:32612")

bkg_sf_cc_plot <- st_transform(bkg_sf_cc_plot, crs = 4326)

coconino_plot <- coconino_sf %>% st_transform(4326)
az_cc_bbox <- st_bbox(coconino_plot)

az_cc_bbox <- c(
  left = az_cc_bbox["xmin"][[1]]-1,
  bottom = az_cc_bbox["ymin"][[1]]-1,
  right = az_cc_bbox["xmax"][[1]]+1,
  top = az_cc_bbox["ymax"][[1]]+1
)

coconino_map <- get_stadiamap(bbox = az_cc_bbox, zoom = 8)

# plot
ggmap(coconino_map) + labs(title = "Coconino County Naturally Caused Large Wildfire Incidence", subtitle = "Background process Y(s)=0 points") + theme_minimal() +
  geom_sf(data = coconino_plot, fill = "gray70", alpha = 0.5, color = "black", size = 5, inherit.aes = FALSE) +
  # geom_sf(data=wf_sf_cc_plot, shape = 21, size = 0.9, 
          # color = "orangered3", fill = "orangered3", inherit.aes = FALSE) +
  geom_sf(data=bkg_sf_cc_plot, shape = 4, size = 1.1, color = "red4", inherit.aes = FALSE)

```
